spring:
  application:
    name: gateway-viacep-cosignado
  jackson:
      property-naming-strategy: SNAKE_CASE

springdoc:
  swagger-ui:
    path: /documentacao

server:
  forward-headers-strategy: native

integrations:
  viacep:
    base-url: https://viacep.com.br/ws